# -*- coding: utf-8 -*-
"""total-commission.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Atimangojackline/c591b8d6ac3fc178b70b8eefbfd8244d/total-commission.ipynb
"""

total_sale_amount= int(input("Enter total sales "))
Total_company_revenue=int(input("Enter total company revenue"))
No_of_leads_generated=int(input("Enter no of leads generated"))

if total_sale_amount <=10000000:
   agency_commission= total_sale_amount*0.03
else:
    agency_commission= (10000000*0.03)+((total_sale_amount)*0.05)
    print("agency_commission")

if Total_company_revenue <=1000000000:
   company_commission =Total_company_revenue*0.0005
else:
    company_commission=(1000000000*0.0005)+((Total_company_revenue-1000000000)*0.0007)
    print("company_commission")

lead_commission = 0
if No_of_leads_generated > 0:
    for i in range(1, No_of_leads_generated+1):
        lead_commission += i * 100

total_commission=agency_commission + company_commission + lead_commission

print("Agency Commission: {}".format(agency_commission))
print("Company Commission: {}".format(company_commission))
print("Lead Commission: {}".format(lead_commission))
print("Total Commission: {}".format(total_commission))